name: CI
on:
  push:
    branches: [ main ]
env:
  PROJECT_NAME: DonPAWA-Adventure
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Download GB Studio
        uses: actions/checkout@v4
        with:
          repository: chrismaltby/gb-studio
          path: gb-studio
      - name: Install gb-studio
        run: cd gb-studio && npm_config_yes=true npx yarn-audit-fix
      - name: Generate Installer
        run: cd gb-studio && npm run make:cli && npm link
      - name: Build Web Version
        run: gb-studio-cli make:web ${PROJECT_NAME}/${PROJECT_NAME}.gbsproj out/web && zip -r ${PROJECT_NAME}-web.zip out/web
      - name: Build ROM
        run: gb-studio-cli make:rom ${PROJECT_NAME}/${PROJECT_NAME}.gbsproj out/rom && zip -r ${PROJECT_NAME}-rom.zip out/rom
      - name: Check Results
        run: ls -last
      - name: Archive Web Game
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.PROJECT_NAME }}-web.zip
      - name: Archive ROM Game
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.PROJECT_NAME }}-rom.zip
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     draft: false
      #     prerelease: false
      # - name: Upload Release Asset
      #   id: upload-release-asset 
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./my-artifact.zip
      #     asset_name: my-artifact.zip
      #     asset_content_type: application/zip