name: CI
on:
  push:
    branches: [ main ]
env:
  PROJECT_NAME: DonPAWA-Adventure
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Download GB Studio
        uses: actions/checkout@v4
        with:
          repository: chrismaltby/gb-studio
          path: gb-studio
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Install gb-studio
        run: cd gb-studio && npm_config_yes=true npx yarn-audit-fix
      - name: Generate Installer
        run: cd gb-studio && npm run make:cli && npm link
      - name: Build Web Version
        run: gb-studio-cli make:web ${PROJECT_NAME}/${PROJECT_NAME}.gbsproj out/web
      - name: Build ROM
        run: gb-studio-cli make:rom ${PROJECT_NAME}/${PROJECT_NAME}.gbsproj out/rom
      - name: Check Results
        run: ls -last
      - name: Archive Web Game
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PROJECT_NAME }}-web.zip
          path: out/web
      - name: Archive ROM Game
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PROJECT_NAME }}-rom.zip
          path: out/rom