name: CI
on:
  push:
    branches: [ main ]
env:
  PROJECT_PATH: DonPAWA-Adventure
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download GB Studio
        uses: actions/checkout@master
        with:
          repository: chrismaltby/gb-studio
      - name: Install gb-studio
        run: npm_config_yes=true npx yarn-audit-fix
      - name: Generate Installer
        run: npm run make:cli && npm link
      #- name: Install GB Studio
      #  id: install-gbs
      #  run: npm -g install gb-studio-cli
      # - name: Generate Web ROM
      #  run: gbstudio build ${PROJECT_PATH} --web
      - name: Execute Code
        run: gb-studio-cli -V