name: CI
on:
  push:
    branches: [ main ]
jobs:
  install-gb-studio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install GB Studio
        id: install-gbs
        run: npm -g install gb-studio-cli
      - run: ls -last .
      - name: Generate Web ROM
        run: gbstudio build . --web
        
